services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URI: 
      JWT_SECRET: 
      SENDGRID_API_KEY: 
      SENDGRID_FROM_EMAIL:
    ports:
      - 3000:3000
  
  db:
    image: mongo
    restart: always
    volumes:
      - <your_volume>:/data/db
    ports:
      - 127.0.0.1:27017:27017
